"""empty message

Revision ID: abe5c69bab68
Revises: 
Create Date: 2021-10-24 21:52:19.821848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abe5c69bab68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_purse_user_idx', table_name='purse')
    op.drop_index('purse_id_UNIQUE', table_name='purse')
    op.drop_table('purse')
    op.drop_index('user_id_UNIQUE', table_name='user')
    op.drop_table('user')
    op.drop_index('fk_transfer_purse1_idx', table_name='transfer')
    op.drop_index('fk_transfer_purse2_idx', table_name='transfer')
    op.drop_index('fk_transfer_user1_idx', table_name='transfer')
    op.drop_index('fk_transfer_user2_idx', table_name='transfer')
    op.drop_index('transfer_id_UNIQUE', table_name='transfer')
    op.drop_table('transfer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('transfer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quanity_funds', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('user_id_from', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id_to', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purse_id_from', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purse_id_to', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['purse_id_from'], ['purse.purse_id'], name='fk_transfer_purse1'),
    sa.ForeignKeyConstraint(['purse_id_to'], ['purse.purse_id'], name='fk_transfer_purse2'),
    sa.ForeignKeyConstraint(['user_id_from'], ['user.user_id'], name='fk_transfer_user1'),
    sa.ForeignKeyConstraint(['user_id_to'], ['user.user_id'], name='fk_transfer_user2'),
    sa.PrimaryKeyConstraint('transfer_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('transfer_id_UNIQUE', 'transfer', ['transfer_id'], unique=False)
    op.create_index('fk_transfer_user2_idx', 'transfer', ['user_id_to'], unique=False)
    op.create_index('fk_transfer_user1_idx', 'transfer', ['user_id_from'], unique=False)
    op.create_index('fk_transfer_purse2_idx', 'transfer', ['purse_id_to'], unique=False)
    op.create_index('fk_transfer_purse1_idx', 'transfer', ['purse_id_from'], unique=False)
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id_UNIQUE', 'user', ['user_id'], unique=False)
    op.create_table('purse',
    sa.Column('purse_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('funds', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='fk_purse_user'),
    sa.PrimaryKeyConstraint('purse_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('purse_id_UNIQUE', 'purse', ['purse_id'], unique=False)
    op.create_index('fk_purse_user_idx', 'purse', ['user_id'], unique=False)
    # ### end Alembic commands ###
